# PATH TO SAVE RESULTS
model_name:             'CatBoost'
model_dir:              '../models/CatBoost/'
plot_dir:               '../plots/CatBoost/'
report_dir:             '../reports/CatBoost/'

seed:                   100
n_cores:                20

# TRAIN DATA READING
path_train_data:        '../data/2_samples/sample_train.tsv.gz'
nrows:                  1000000000
validate_size:          0.30
test_size:              0.15
kFolds:                 5
confidence:             0.95

# TRAIN PARAMETERS
iterations:             1000
